// WebP format of images
export const p1 = require("../../assets/p1.webp");
export const p2 = require("../../assets/p2.webp");
export const p3 = require("../../assets/p3.webp");
export const p4 = require("../../assets/p4.webp");
export const p5 = require("../../assets/p5.webp");
export const p6 = require("../../assets/p6.webp");
export const p7 = require("../../assets/p7.webp");
export const p8 = require("../../assets/p8.webp");
export const p9 = require("../../assets/p9.webp");
